[connections.postgresql]
    type="postgresql"
    dialect="postgresql"
    username="postgres"
    password="password"
    host="localhost" # IP or URL
    port=5432 # Port number
    database="etl_database_1" # Database name
